sosohandiary/BE

build.gradle
src/main/java/com/hanghae/sosohandiary/auth/JwtAuthFilter.java
src/main/java/com/hanghae/sosohandiary/auth/JwtUtil.java
src/main/java/com/hanghae/sosohandiary/config/WebSecurityConfig.java
src/main/java/com/hanghae/sosohandiary/domain/member/controller/MemberController.java
src/main/java/com/hanghae/sosohandiary/domain/member/dto/KakaoMemberInfoDto.java
src/main/java/com/hanghae/sosohandiary/domain/member/entity/Member.java
src/main/java/com/hanghae/sosohandiary/domain/member/repository/MemberRepository.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java
src/main/java/com/hanghae/sosohandiary/security/MemberDetailsImpl.java
src/main/java/com/hanghae/sosohandiary/security/MemberDetailsServiceImpl.java
src/main/java/com/hanghae/sosohandiary/utils/MessageDto.java

카카오 로그인 OAuth2.0 구현
- 특이사항1 : 포스트맨에서 꼭 확인 해보기

Feat: 카카오 로그인 OAuth2.0 구현 #3

---

src/main/java/com/hanghae/sosohandiary/domain/comment/controller/CommentController.java
src/main/java/com/hanghae/sosohandiary/domain/comment/dto/CommentRequestDto.java
src/main/java/com/hanghae/sosohandiary/domain/comment/dto/CommentResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/comment/entity/Comment.java
src/main/java/com/hanghae/sosohandiary/domain/comment/repository/CommentRepository.java
src/main/java/com/hanghae/sosohandiary/domain/comment/service/CommentService.java
src/main/java/com/hanghae/sosohandiary/exception/ErrorHandling.java

feat : 다이어리 속지 댓글 작성 #9

---

src/main/java/com/hanghae/sosohandiary/domain/comment/controller/CommentController.java
src/main/java/com/hanghae/sosohandiary/domain/comment/entity/Comment.java
src/main/java/com/hanghae/sosohandiary/domain/comment/service/CommentService.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/repository/DiaryDetailRepository.java
src/main/java/com/hanghae/sosohandiary/exception/ErrorHandling.java

> feat : 다이어리 속지 댓글 수정 #11
- comment의 타입이 String임.

feat : 다이어리 속지 댓글 수정 #11

---

src/main/java/com/hanghae/sosohandiary/domain/comment/service/CommentService.java

fix : 다이어리 속지 댓글 수정 #13

---

src/main/java/com/hanghae/sosohandiary/auth/JwtAuthFilter.java
src/main/java/com/hanghae/sosohandiary/domain/diary/entity/Diary.java
src/main/java/com/hanghae/sosohandiary/domain/diary/service/DiaryService.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/controller/DiaryDetailController.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/dto/DiaryDetailResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/entity/DiaryDetail.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/repository/DiaryDetailRepository.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/service/DiaryDetailService.java
src/main/java/com/hanghae/sosohandiary/domain/image/entity/DiaryDetailImage.java
src/main/java/com/hanghae/sosohandiary/domain/image/entity/DiaryImage.java
src/main/java/com/hanghae/sosohandiary/domain/image/repository/DiaryDetailImageRepository.java
src/main/java/com/hanghae/sosohandiary/domain/image/repository/DiaryImageRepository.java
src/main/java/com/hanghae/sosohandiary/domain/member/controller/MemberController.java
src/main/java/com/hanghae/sosohandiary/domain/member/repository/MemberRepository.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/KakaoMemberService.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java
src/main/java/com/hanghae/sosohandiary/exception/ApiException.java
src/main/java/com/hanghae/sosohandiary/exception/ErrorHandling.java
src/main/java/com/hanghae/sosohandiary/security/MemberDetailsImpl.java
src/main/java/com/hanghae/sosohandiary/security/MemberDetailsServiceImpl.java
src/main/java/com/hanghae/sosohandiary/utils/s3/S3Service.java

- 특이사항1 : 예외처리 Enum타입 추가안함 추후 변경해야함

Feat/diary detail#8

---

src/main/java/com/hanghae/sosohandiary/domain/comment/controller/CommentController.java
src/main/java/com/hanghae/sosohandiary/domain/comment/service/CommentService.java
src/main/java/com/hanghae/sosohandiary/exception/ErrorHandling.java

fix : 다이어리 속지 댓글 삭제 #16

---

src/main/java/com/hanghae/sosohandiary/config/WebSecurityConfig.java
src/main/java/com/hanghae/sosohandiary/domain/member/controller/MemberController.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/KakaoMemberService.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java
src/main/java/com/hanghae/sosohandiary/exception/ErrorHandling.java

Feat: 카카오 로그인 서버 적용

---

src/main/java/com/hanghae/sosohandiary/domain/diary/controller/DiaryController.java

feat: diary 전체 조회 url 수정 #8

---

src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/controller/MyFriendsListController.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/entity/FriendRequest.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/entity/MyFriendsList.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/repository/FriendRequestRepository.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/repository/MyFriendsListRepository.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/service/MyFriendsListService.java

Feat: 친구 요청 등록 API
- 특이사항1 : 친구 등록창까지 API 등록 되어 있음. 추가 개발 예정.

Feat: 친구 요청 등록 API #22

---

src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/controller/MyFriendsListController.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/dto/MyFriendResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/repository/FriendRequestRepository.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/service/MyFriendsListService.java

Feat: 친구등록 요청 조회 API #24
- 특이사항1 : 로그인한 아이디 기준으로 내림차순으로 잘 조회되는지 확인하기.

Feat: 친구등록 요청 조회 API #24

---

src/main/java/com/hanghae/sosohandiary/domain/member/dto/JoinRequestDto.java
src/main/java/com/hanghae/sosohandiary/domain/member/dto/KakaoMemberInfoDto.java
src/main/java/com/hanghae/sosohandiary/domain/member/entity/Member.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/KakaoMemberService.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java

회원정보 추가에 따른 회원가입, 로그인, 카카오 로그인 수정
- 특이사항1 : 없음

Fix: 회원정보 추가에 따른 회원가입, 로그인, 카카오 로그인 수정

---

src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/service/MyFriendsListService.java

Feat: 친구등록 수락 API 구현 #27
- 특이사항1: 로그인 한 회원만 삭제되도록 구현.
- 특이사항2: 양 측 모두가 수락되도록 구현.

Feat: 친구등록 수락 API 구현 #27

---

src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/controller/MyFriendsListController.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/dto/FriendListResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/repository/MyFriendsListRepository.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/service/MyFriendsListService.java

Feat: 내가 등록한 친구 조회(임시)

---

src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/repository/MyFriendsListRepository.java
src/main/java/com/hanghae/sosohandiary/domain/myfriendsList/service/MyFriendsListService.java

Feat: 내가 등록한 친구 조회 #30

---

src/main/java/com/hanghae/sosohandiary/domain/diary/controller/DiaryController.java
src/main/java/com/hanghae/sosohandiary/domain/diary/service/DiaryService.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/service/DiaryDetailService.java
src/main/java/com/hanghae/sosohandiary/domain/friend/controller/FriendRequestController.java
src/main/java/com/hanghae/sosohandiary/domain/friend/service/FriendsRequestService.java

이미지 없이 다이어리 작성 가능하게
- 특이사항1 : 없음

feat: 이미지 null 값 허용 #41

---

src/main/java/com/hanghae/sosohandiary/domain/member/dto/JoinRequestDto.java
src/main/java/com/hanghae/sosohandiary/domain/member/dto/KakaoMemberInfoDto.java
src/main/java/com/hanghae/sosohandiary/domain/member/entity/Gender.java
src/main/java/com/hanghae/sosohandiary/domain/member/entity/Member.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/KakaoMemberService.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java

Fix: 회원가입 및 로그인 기능
- 특이사항1 : 없음
- 특이사항2

Fix: 회원가입 및 로그인 기능

---

src/main/java/com/hanghae/sosohandiary/domain/diary/repository/DiaryRepository.java
src/main/java/com/hanghae/sosohandiary/domain/mypage/controller/MypageController.java
src/main/java/com/hanghae/sosohandiary/domain/mypage/service/MypageService.java

마이페이지 나의 다이어리 수 조회
- 특이사항1 : 없음

Feat: 마이페이지 나의 다이어리 수 조회

---

src/main/java/com/hanghae/sosohandiary/domain/diary/entity/Diary.java
src/main/java/com/hanghae/sosohandiary/domain/diary/service/DiaryService.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/entity/DiaryDetail.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/service/DiaryDetailService.java

uploadpath 로 되어있던 이미지 변수명 img 로 변경
- 특이사항1 : 없음

uploadpath 로 되어있던 이미지 변수명 img 로 변경

---

src/main/java/com/hanghae/sosohandiary/domain/like/controller/LikeController.java
src/main/java/com/hanghae/sosohandiary/domain/like/entity/Likes.java
src/main/java/com/hanghae/sosohandiary/domain/like/repository/LikesRepository.java
src/main/java/com/hanghae/sosohandiary/domain/like/service/LikeService.java

Feat: 좋아요 기능 API 구현 #49

---

src/main/java/com/hanghae/sosohandiary/domain/decoration/controller/DecorationController.java
src/main/java/com/hanghae/sosohandiary/domain/decoration/entity/Decoration.java
src/main/java/com/hanghae/sosohandiary/domain/decoration/repository/DecorationRepository.java
src/main/java/com/hanghae/sosohandiary/domain/decoration/service/DecorationService.java

Test: 꾸미기 기능 저장 테스트 #51

---

src/main/java/com/hanghae/sosohandiary/domain/decoration/controller/DecorationController.java
src/main/java/com/hanghae/sosohandiary/domain/decoration/service/DecorationService.java

Test: 꾸미기 기능 get

---

src/main/java/com/hanghae/sosohandiary/domain/member/dto/MemberResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/mypage/controller/MypageController.java
src/main/java/com/hanghae/sosohandiary/domain/mypage/service/MypageService.java

Feat: 마이페이지 - 내 친구 목록 보여주기
- 특이사항1 : 없음

Feat: 마이페이지 - 내 친구 목록 보여주기

---

src/main/java/com/hanghae/sosohandiary/domain/friend/controller/FriendRequestController.java

친구 추가 요청 controller url 수정
- 특이사항1 : 없음

fix: 친구 요청 url 수정 #47

---

src/main/java/com/hanghae/sosohandiary/domain/mypage/dto/MypageProfileResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/mypage/service/MypageService.java

Fix: 마이페이지 - 프로필 조회
- 특이사항1 : 없음

Fix: 마이페이지 - 프로필 조회

---

src/main/java/com/hanghae/sosohandiary/domain/diary/controller/DiaryController.java
src/main/java/com/hanghae/sosohandiary/domain/diary/dto/DiaryResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/diary/repository/DiaryRepository.java
src/main/java/com/hanghae/sosohandiary/domain/diary/service/DiaryService.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/controller/DiaryDetailController.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/dto/DiaryDetailResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/repository/DiaryDetailRepository.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/service/DiaryDetailService.java

Diary, DiaryDetail 페이징
- 특이사항1 : 없음

Feat/paging add #61

---

src/main/java/com/hanghae/sosohandiary/domain/member/dto/MemberResponseDto.java

Fix: 마이페이지 - 내 친구 목록 보여주기
- 특이사항1 : 없음

Fix: 마이페이지 - 내 친구 목록 보여주기

---

src/main/java/com/hanghae/sosohandiary/domain/diary/controller/DiaryController.java
src/main/java/com/hanghae/sosohandiary/domain/diary/service/DiaryService.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/controller/DiaryDetailController.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/service/DiaryDetailService.java
src/main/java/com/hanghae/sosohandiary/utils/page/PageCustom.java
src/main/java/com/hanghae/sosohandiary/utils/page/PageableCustom.java

📕 제목
페이징 response custom
📗 작업 내용
구현 내용 및 작업 했던 내역
작업내용1 : 페이징 response 형식 변경
📘 PR 특이 사항
PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
특이사항1 : 없음

Feat/paging customizing #61

---

src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java
src/main/java/com/hanghae/sosohandiary/utils/MessageDto.java

Fix: 로그인 Response 수정
- 특이사항1 : 없음

Fix: 로그인 Response 수정

---

src/main/java/com/hanghae/sosohandiary/domain/member/repository/MemberRepository.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java
src/main/java/com/hanghae/sosohandiary/exception/ErrorHandling.java

Fix: 회원가입 시 닉네임 중복체크 

---

src/main/java/com/hanghae/sosohandiary/domain/friend/repository/FriendListRepository.java
src/main/java/com/hanghae/sosohandiary/domain/friend/service/FriendsRequestService.java

fix: 친구요청 시 상대방이 먼저 등록했을 경우, 이미 친구 등록되어 있을 경우 exception 처리 #72

fix: 친구요청 시 상대방이 먼저 등록했을 경우, 이미 친구 등록되어 있을 경우 exception 처리 #72

---

src/main/java/com/hanghae/sosohandiary/domain/diarydetil/dto/DiaryDetailRequestDto.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetil/entity/DiaryDetail.java

Refactor : 다이어리 속지 꾸미기 기능 추가, 이미지 멀티파일 삭제 #78
- 특이사항1 : Json 스트링 잘 들어가는지 확인.

Refactor : 다이어리 속지 꾸미기 기능 추가, 이미지 멀티파일 삭제 #78

---

src/main/java/com/hanghae/sosohandiary/domain/friend/Enum/StatusFriend.java

Refactor: 친구 추가 테이블 하나로 변경. 상태코드 추가. #87

---

src/main/java/com/hanghae/sosohandiary/domain/comment/controller/CommentController.java
src/main/java/com/hanghae/sosohandiary/domain/comment/dto/CommentAlarmResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/comment/entity/Comment.java
src/main/java/com/hanghae/sosohandiary/domain/comment/repository/CommentRepository.java
src/main/java/com/hanghae/sosohandiary/domain/comment/service/CommentService.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetail/dto/DiaryDetailResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetail/entity/DiaryDetail.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetail/service/DiaryDetailService.java
src/main/java/com/hanghae/sosohandiary/domain/invite/controller/InviteController.java
src/main/java/com/hanghae/sosohandiary/domain/invite/dto/InviteResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/invite/repository/InviteRepository.java
src/main/java/com/hanghae/sosohandiary/domain/invite/service/InviteService.java
src/main/java/com/hanghae/sosohandiary/domain/like/controller/LikeController.java
src/main/java/com/hanghae/sosohandiary/domain/like/dto/LikesResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/like/entity/Likes.java
src/main/java/com/hanghae/sosohandiary/domain/like/repository/LikesRepository.java
src/main/java/com/hanghae/sosohandiary/domain/like/service/LikeService.java
src/main/java/com/hanghae/sosohandiary/exception/ErrorHandling.java

댓글, 좋아요, 공유 다이어리 알림 기능 추가
- 특이사항1 : 없음

댓글, 좋아요, 공유 다이어리 알림 기능 추가

---

src/main/java/com/hanghae/sosohandiary/domain/diary/controller/DiaryController.java
src/main/java/com/hanghae/sosohandiary/domain/diary/repository/DiaryRepository.java
src/main/java/com/hanghae/sosohandiary/domain/diary/service/DiaryService.java

PRIVATE 다이어리 조회 페이징 삭제
- 특이사항1 : 없음

Feat : PRIVATE 다이어리 조회 페이징 삭제

---

src/main/java/com/hanghae/sosohandiary/domain/member/controller/MemberController.java
src/main/java/com/hanghae/sosohandiary/domain/member/dto/MemberResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java

Fix: 회원검색에 친구 상태코드가 나오도록 수정. #103

Fix: 회원검색에 친구 상태코드가 나오도록 수정. #103

---

src/main/java/com/hanghae/sosohandiary/auth/JwtAuthFilter.java
src/main/java/com/hanghae/sosohandiary/domain/friend/controller/FriendController.java
src/main/java/com/hanghae/sosohandiary/domain/member/controller/MemberController.java
src/main/java/com/hanghae/sosohandiary/domain/member/dto/MemberMessageDto.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/KakaoMemberService.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java
src/main/java/com/hanghae/sosohandiary/utils/MessageDto.java

MessageDto와 MemberMessageDto 나누기
- 특이사항1 : 없음

Refactor: MessageDto와 MemberMessageDto 나누기 

---

src/main/java/com/hanghae/sosohandiary/domain/friend/repository/FriendRepository.java
src/main/java/com/hanghae/sosohandiary/domain/mypage/service/MyPageService.java

친구요청 accpted일 시 친구 수 증가로 나오게끔 수정
- 특이사항1 : 없음

Fix: 친구요청 accpted일 시 친구 수 증가로 나오게끔 수정 

---

src/main/java/com/hanghae/sosohandiary/domain/comment/dto/CommentResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/friend/dto/FriendResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/friend/service/FriendService.java
src/main/java/com/hanghae/sosohandiary/domain/member/dto/MemberResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/member/service/MemberService.java

Feat: 프로필 사진 추가하기 기능

---

src/main/java/com/hanghae/sosohandiary/domain/comment/controller/CommentController.java
src/main/java/com/hanghae/sosohandiary/domain/comment/dto/CommentAlarmResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/comment/entity/Comment.java
src/main/java/com/hanghae/sosohandiary/domain/comment/service/CommentService.java
src/main/java/com/hanghae/sosohandiary/domain/friend/controller/FriendController.java
src/main/java/com/hanghae/sosohandiary/domain/friend/dto/FriendResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/friend/entity/Friend.java
src/main/java/com/hanghae/sosohandiary/domain/friend/service/FriendService.java
src/main/java/com/hanghae/sosohandiary/domain/invite/controller/InviteController.java
src/main/java/com/hanghae/sosohandiary/domain/invite/dto/InviteResponseDto.java
src/main/java/com/hanghae/sosohandiary/domain/invite/entity/Invite.java
src/main/java/com/hanghae/sosohandiary/domain/invite/service/InviteService.java

알림 확인 기능 구현

---

src/main/java/com/hanghae/sosohandiary/domain/diary/service/DiaryService.java
src/main/java/com/hanghae/sosohandiary/domain/diarydetail/repository/DiaryDetailRepository.java

Fix : 다이어리 삭제시 삭제 안되는 오류 수정
- 특이사항1 : 없음

Fix : 다이어리 삭제시 삭제 안되는 오류 수정
